# Lesson 3

## Importing Libraries

In [2]:
import numpy as np # make sure numpy is installed by using pip install numpy


- Libraries are super useful and quick to use if you want some specific functionality
- Where to find all libraries? ​https://pypi.org/ 
- check out the documentation
- How to use a library? Install library (pip-command!) pip install libray
- Import library in script: import \<library\> 
- Put your import above, so you have an overview


In [3]:
# import standard libraries => do not need to download, just use import
import random as rd
import math 
import datetime 
# print a random number from 0 to 10
print(rd.randrange(0,11))
# print the current date & time
print(datetime.datetime.now())

10
2023-02-27 15:11:15.624717


In [4]:
import numpy
import numpy as np
# import a single functionality from the package
from numpy import arange 

## Numpy

In [6]:
# Create an array and print it
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(array)


[1 2 3 4 5 6 7 8]


### types

In [6]:
# An array is fixed sized and the elements are always the same type
array = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(type(array)) # numpy array
print(array.dtype) # int32
# conversion to float
print(array.astype('f'))
string_array = np.array(["Hello","World"])
print(type(string_array)) # numpy array
print(string_array.dtype) # U5 = unicode string of 5 bytes
"""
from https://www.w3schools.com/python/numpy/numpy_data_types.asp
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.
Below is a list of all data types in NumPy and the characters used to represent them.
    i - integer
    b - boolean
    u - unsigned integer
    f - float
    c - complex float
    m - timedelta
    M - datetime
    O - object
    S - string
    U - unicode string
    V - fixed chunk of memory for other type ( void )
"""
# when converting always make sure that the conversion is possible:
# Converting the following array to an integer will result in an error
# number_array = np.array('a','b','c') -> ERROR
# You cannot convert 'a' to an Integer

<class 'numpy.ndarray'>
int32
[1. 2. 3. 4. 5. 6. 7. 8.]
<class 'numpy.ndarray'>
<U5


In [12]:
# Differences between list & array
numbers_list = [1,2,3]
numbers_array = np.array([1,2,3])
print(numbers_list*2)
print(numbers_array*2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


### Common functions

In [7]:
# shape
numbers_array = np.array([[1,2,3],[4,5,6]])
print(numbers_array.shape)
print(numbers_array)
# dimensions (count of the shape)
print("The dimension of the array is",numbers_array.ndim)

(2, 3)
[[1 2 3]
 [4 5 6]]
2


In [13]:
# Fill up an array by starting at 0 and adding 2 everytime until you hit 6 (7-1) -> exlusive
numbers = np.arange(0,7,2)
print(numbers)
# Fill up an 2D array with zeros
numbers = np.zeros((2,2))
print(numbers)

[0 2 4 6]
[[0. 0.]
 [0. 0.]]


In [14]:
# Fill up an array with 5 rows and two columns with the number "4"
print(np.full((5,2), 4))
# prints out a matrix (2d array) of 0s with a diagonal 1
print(np.eye(4))

[[4 4]
 [4 4]
 [4 4]
 [4 4]
 [4 4]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
# slicing
array = np.random.randint(0,11,(5,4)) # create random array
print(array)
print(array[2:4]) # print the index 2 of the rows (third row) until the index 4 of the rows.


[[ 0  0  1  1]
 [ 2 10  0  9]
 [ 5 10  4 10]
 [ 1  1  7  5]
 [ 3 10 10  1]]
[[ 5 10  4 10]
 [ 1  1  7  5]]
[3 4]


In [32]:
# Random
# Create a array with one row and 4 columns 
# filled with random float numbers between 0 and 1
print(np.random.random((1,4))) 
# Create an array with 4 rows and 4 columns
# filled with random integers between -10 and 10 (exclusive)                                   
print(np.random.randint(-10, 10, (4,4)))  

[[0.71010124 0.41626439 0.8768812  0.62473825]]
[[-4 -2 -6  8]
 [-2  2 -5  7]
 [-4  9  1  0]
 [-7  5 -2 -1]]


In [21]:
# where function
array = np.array([1, 2, 3, 5, 5, 6, 7, 8])
# where the array are odd add one, else output the same element back
# Will result in an array full with even numbers
print(np.where(array%2==1,array+1,array)) 


[2 2 4 6 6 6 8 8]


In [33]:
# sum, min, max, sqrt, cumsum
array = np.array([1, 2, 3, 5, 5, 6, 7, 8])
print("sum",array.sum())
print("min",array.min())
print("max",array.max())
print("sqrt",np.sqrt(array)) # Take the square root of all the elements in an array
print("cum sum",array.cumsum()) # sum cumulative. For more information: see https://mathworld.wolfram.com/CumulativeSum.html
print("power",np.power(array,2)) # square all elements in an array
print(np.any(array > 3)) # Is any element bigger than 3 -> True
print(np.all(array > 3)) # Are all elements bigger than 3 -> False


sum 37
min 1
max 8
sqrt [1.         1.41421356 1.73205081 2.23606798 2.23606798 2.44948974
 2.64575131 2.82842712]
cum sum [ 1  3  6 11 16 22 29 37]
power [ 1  4  9 25 25 36 49 64]
True


## Pythonic code

In [54]:
# The zen of Pyton, by Tim Peters
import this 
print(this.d)

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!
{'A': 'N', 'B': 'O', 'C': 'P', 'D': 'Q', 'E': 'R', 'F': 'S', 'G': 'T', 'H': 'U', 'I': 'V', 'J': 'W', 'K': 'X', 'L': 'Y', 'M': 'Z', 'N': 'A', 'O

In [32]:
# Pythonic looping
# Use the following for a for loop
random_numbers = [1,58,46,2,45]
for number in random_numbers:
    print(number)

"""
Bad practice! Don't do the following:
random_numbers = [1,58,46,2,45]
for i in range(0,len(random_numbers)):
    print(random_numbers[i])
"""
#Pythonic dictionaries

data = ["apple","banana","mango","kiwi"]
colors = ["green", "yellow","orange", "green"]

# Create a dictionary of pairs
dc = dict(zip(data, colors))


# Loop dictionary
for key, val in dc.items():
    print(key, val)

# Not pythonic: DONT USE

# Create a dictionary of pairs
dc = {}
for key, val in zip(data, colors):
    dc[key] = val

# Loop dictionary
for key in dc:
    print(key, dc[key])



1
58
46
2
45


## Extra exercises        

- Merge two arrays of integers into one, sorted in ascending order.
- Reverse the order of elements in an array of integers.
- Count the number of even and odd numbers in an array of integers.
- Find the second largest number in an array of integers.

In [35]:
# - Count the number of even and odd numbers 
# in an array of integers.
random_array = np.random.randint(0,11,(7,))
print(random_array)
even_numbers = 0
for i in random_array:
    if i%2==0:
        even_numbers+=1
print("The even numbers: ",even_numbers)
print("The odd numbers: ",len(random_array)-even_numbers)
# How to do it easier in numpy?
# get all the numbers that satisfy the condition random_array % 2 == 0
# Sum these conditions together
# True = 1, False = 0
# So for array [2 3 5 5 8 7 0]
# You get array [True False False False True False True]
# When you sum these together the sum function counts True as 1
# and False as 0. So the sum is the amount of even numbers 
even_count = np.sum(random_array % 2 == 0) 
print(even_count)

[2 3 5 5 8 7 0]
The even numbers:  3
The odd numbers:  4
3


In [72]:
#Reverse the order of elements in an array of integers.
random_array = np.random.randint(0,11,(7,))
print(random_array)
# use the -1 step to get the reverse of the array
print("The reverse: ",random_array[::-1])

[ 9 10  3  3  7  6  1]
The reverse:  [ 1  6  7  3  3 10  9]


In [36]:
# Calculate the sum of an array
random_array = np.random.randint(0,11,(7,))
print(random_array)
print(random_array.sum())
# alternative way
print(np.sum(random_array))

[ 5  5  2 10  9  3  1]
35
35
